<?php
$prof = array(
'Accounting' => array(
    'Assistant Accountant',
    'Production Accountant',
    'Senior Production Accountant',
	'Other / Accounting /',
),

'Art & Set' => array(
    'Art Buyer',
    'Art Department Assistant',
    'Art Department Coordinator',
    'Art Director',
    'Art Finisher',
    'Art Runner',
    'Assistant Art Director',
    'Assistant Buyer',
    'Construction Coordinator',
    'Creature Designer',    
    'Draughtsman',
    'Food Stylist',      
    'Graphic Artist',
    'Junior Draughtsman',
    'Leadman',
    'Matt Painting',      
    'Model Maker',
    'Moldmaker',
    'Production Designer',
    'Sculptor',
    'Set Construction',     
    'Set Decorator',
    'Set Designer',
    'Set Painting/Scenic',      
    'Sign Writer',      
    'Supervising Art Director',
    'Swing',      
    'Texture Artist',
	'Other / Art & Set  /',
	),

'Camera' => array(
    'Aerial Camera Operator',
    'Aerial Specialist', 
    'Assistant Camera',
    'Assistant Camera (1st)',
    'Assistant Camera (2nd)',
    'Camera Operator',
    'Director of Photography',
    'Focus Puller',
    'Jib Assistant',
    'Jib Operator',
    'Loader',      
    'Multicamera Director',     
    'Steadicam Operator',
    'Still Photographer',
    'Studio Videographer',      
    'Videographer: EFP',      
    'Videographer: ENG',
    'Other / Camera /',	
),

'Casting & Talent' => array(
    'Agent',
    'Animal Trainer', 
    'Assistant Casting Director',
    'Casting Assistant',
    'Casting Associate',
    'Casting Coordinator',
    'Casting Director',
    'Celebrity Booker',     
    'Dialogue Coach',      
    'Talent Assistant',
    'Talent Booker',        
    'Talent Manager',
    'Talent Wrangler',
    'Voiceover Artist',
    'Other / Casting & Talent /',	
),

'Craft Services' => array(
    'Caterer',      
    'Craft Service', 
    'Other / Craft Services /',
),

'Directorial' => array(
    'Assistant Director (1st)',
    'Assistant Director (2nd 2nd)',
    'Assistant Director (2nd)',
    'Director',     
    'Director, Commercials',     
    'Director, Feature Film',     
    'Director, Music Video',     
    'Director, Reality Television',
    'Director, Television',
    'Director\'s Assistant',     
    'DV Director',
    'Industiral Director',
    'Multicamera Director',
    'News Director',
    'Second Unit Director',
    'Technical Director',
    'Other /Directorial/'
),
'Editors & Animators' => array(
    'Animator', 
    'Animator (with Live Action)',  
    'Assistant Dialogue Editor', 
    'Assistant Editor', 
    'Assistant Story Editor', 
    'Colorist', 
    'Compositor',       
    'Computer Effects',       
    'Dailies Editor', 
    'Dialogue Editor', 
    'Digital Compositor', 
    'Editor', 
    'Editor (After Effects)',       
    'Editor (Avid)',         
    'Editor (Final Cut Pro)',       
    'Editor (Offline)',       
    'Editor (Online)',       
    'Editorial Assistant', 
    'Executive Story Editor', 
    'Lead Assistant Editor', 
    'Lead Compositor', 
    'Motion Graphics',      
    'News Editor',       
    'Picture Editor',         
    'Senior Character Animator', 
    'Story Editor', 
    'Supervising Editor', 
    'Supervising Sound Editor', 
    'Supervising Story Editor',
    'Video Editor',
	'Other / Editors & Animators /'
	),      

'Executives' => array(
    'Development Executive', 
    'Executive', 
    'Executive Assistant', 
    'Executive in Charge of Production', 
    'Executive Producer', 
    'Network Executive', 
    'Personal Assistant',       
    'Post-Production Executive', 
    'Programming Executive', 
    'Showrunner',
	'Other / Executives /'
),

'Hair & Makeup' => array(
    'Hair Stylist',       
    'Makeup', 
    'Makeup Artist',       
    'Makeup Assistant',  
    'Prosthetic Makeup Artist', 
    'Prosthetics Technician',
	'Other / Hair & Makeup /'
),

'Legal' => array(
    'Lawyer', 
    'Rights & Clearances',
	'Other / Legal /',
),     

'Lighting, Grip & Electric' => array(
    'Aerial Specialist', 
    'Best Boy', 
    'Cable Puller',       
    'Chief Lighting Technician', 
    'Dolly Grip',         
    'Electrician', 
    'Gaffer', 
    'Grip', 
    'Key Grip', 
    'Lighting Designer', 
    'Lighting Director', 
    'Lighting Supervisor',       
    'Lighting Technical Director', 
    'Rigger', 
    'Rigging Electric',       
    'Rigging Grip',
	'Other / Lighting, Grip & Electric /', 
),        


'Locations' => array(
    'Assistant Location Manager',
    'Location Casting Director',
    'Location Manager',
    'Location Scout',      
    'Other / Locations /'
),	


'Marketing' => array(
    'Unit Publicist',
    'Other / Marketing /',	
),


'Post-Production' => array(
    'Animator',
    'Animator (with Live Action)',  
    'Assistant Post-Production Coordinator',
    'Colorist',
    'Compositor',      
    'Computer Effects',      
    'Digital Compositor',
    'Digital Effects Supervisor',
    'Effects Technical Director',
    'Graphic Artist',
    'Lead Compositor',
    'Lead Logger',
    'Logger',    
    'Motion Graphics',      
    'Post-Producer',
    'Post-Production Assistant',
    'Post-Production Coordinator',
    'Post-Production Executive',
    'Post-Production Supervisor',
    'Roto Artist',
    'Runner',      
    'Senior Character Animator',
    'Tape Logger',      
    'Transcriptionist',
    'Other / Post-Production /'	
),

'Producers' => array(
    'Co-Executive Producer',
    'Consultant',
    'Consulting Producer',
    'Coordinating Producer',
    'Co-Producer',
    'Creator',
    'Development Producer',        
    'Executive Producer',
    'Field Producer',
    'Host Producer',
    'Industrial Producer',      
    'Line Producer',
    'News Producer',      
    'Post-Producer',
    'Producer',
    'Promotions Producer',        
    'Segment Producer',
    'Series Producer',      
    'Showrunner',
    'Supervising Producer',
    'Swing',      
    'Television Producer',
    'Other / Producers /'	
),

'Production' => array(
    'Archivist',
    'Assistant to Producer',      
    'Associate Producer',
    'Associate Segment Producer',
    'Fixer',      
    'Key Production Assistant',
    'Key Set Production Assistant',
    'Marine Coordinator',          
    'Personal Assistant',      
    'Production Assistant',
    'Production Associate', 
    'Production Coordinator',
    'Production Manager',
    'Production Supervisor',      
    'Project Manager',      
    'Receptionist',      
    'Researcher',      
    'Runner',      
    'Security Guard',        
    'Specialist Researcher',
    'Stage Manager',      
    'Translator',      
    'Unit Manager',
    'Unit Production Manager',
	'Other / Production /'
),

'Props' => array(
    'Dressing Propman',
    'Property Buyer',
    'Property Maker',      
    'Property Master',
	'Other / Props /'
),

'Sound' => array(
    'ADR Recordist',
    'Audio Assistant',
    'Audio Mixer',
    'Audio Recordist',      
    'Audio Supervisor',
    'Boom Operator',
    'Composer',        
    'Dubbing Mixer',      
    'Dubbing Music Editor',
    'Foley Artist',      
    'Foley Mixer',
    'Music Coordinator',
    'Music Editor',
    'Music Supervisor',
    'Musical Arranger',      
    'Production Sound Mixer',      
    'Re-Recording Mixer',        
    'Score Mixer',
    'Sound Assistant',      
    'Sound Designer',
    'Sound Editor',
    'Sound Engineer',      
    'Sound Playback',      
    'Sound Recordist',      
    'Sound Re-Recording Mixer',
    'Sound Runner',
    'Supervising Sound Editor',
    'Voiceover Artist',
    'Other / Sound /'	
),

'Specialty' => array(
    'Choreographer',      
    'Fitness Trainer',     
    'Fixer',      
    'Marine Coordinator',        
    'Set Medic',            
    'Still Photographer',
    'Studio Teacher',      
    'Translator',
    'Other / Specialty /'	
),

'Story' => array(
    'Executive Story Editor', 
    'Script Coordinator', 
    'Script Supervisor', 
    'Storyboard Artist', 
    'Supervising Story Editor',
	'Other / Story /', 
),

'Student' => array(
    'Intern',     
    'Student',
    'Other / Student /'	
),

'Stunts & FX' => array(
    'Creature Designer',        
    'Creature Effects Supervisor', 
    'Digital Effects Supervisor', 
    'Effects Technical Director', 
    'Mechanical Effects',         
    'Model Maker',
    'Special Effects',       
    'Special Effects Editor',       
    'Special Effects Supervisor', 
    'Special Effects Technician', 
    'Stunt Coordinator', 
    'Stunt Double', 
    'Stunt Driver',         
    'Stunt Performer', 
    'Stunt Safety', 
    'VFX Coordinator',       
    'Visual Effects',
    'Other / Stunts & FX /'	
),

'Technical' => array(
    'Autocue operator',      
    'Broadcast Engineer',      
    'Cable Puller',      
    'Crane Technician',
    'Master Control Operator',      
    'Technical Advisor',
    'Technical Coordinator',
    'Technical Director',
    'Technical Supervisor',
    'Teleprompting',      
    'Video Assist Coordinator',
    'Video Assist Operator',
    'Video Engineer',      
    'Video Playback',
    'VT Operator',
    'Other / Technical /'    
),

'Transportation' => array(
    'Driver',
    'Transportation Captain',
    'Transportation Coordinator',
    'Other / Transportation /'	
),

'Wardrobe' => array(
    'Assistant Buyer',
    'Costume',
    'Costume Designer',
    'Set Costumers',      
    'Wardrobe',
    'Wardrobe Stylist',
    'Other / Wardrobe /'	
),

'Writer' => array(
    'Industrial Writer',      
    'Screen Writer',
    'Teleplay Writer',
    'Writer',
	'Other / Writer /',
)
);


$tmp_company_ar = array(
    0 => array( 'id' => 1, 'name' => 'Commany1', 'image' => ''),
    1 => array( 'id' => 2, 'name' => 'Commany2', 'image' => ''),
    2 => array( 'id' => 3, 'name' => 'Commany3', 'image' => ''),
    3 => array( 'id' => 4, 'name' => 'Commany4', 'image' => ''),
    4 => array( 'id' => 5, 'name' => 'Commany5', 'image' => '')
);

$comp_prof = array(
'Type1' => array(
    'Production Company',
    'PType company 1',
),
'Type2' => array(
    'Type company 1',
    'Type company 2',
),
);

?>